//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTWeb_05.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BanUser
    {
        public int f_IDBan { get; set; }
        public int ProID { get; set; }
    }
}
