//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTWeb_05.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BidDetail
    {
        public int BidID { get; set; }
        public Nullable<int> ProID { get; set; }
        public Nullable<int> f_ID { get; set; }
        public Nullable<decimal> BidPrice { get; set; }
        public Nullable<System.DateTime> TimeAuction { get; set; }
    }
}
