//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTWeb_05.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CmtDetail
    {
        public int Cmt_ID { get; set; }
        public Nullable<int> f_IDPost { get; set; }
        public string f_Name { get; set; }
        public string f_Email { get; set; }
        public Nullable<int> f_RatingPoint { get; set; }
        public Nullable<int> f_IDRecevie { get; set; }
        public string TextCmt { get; set; }
    }
}
